/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const LinkId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'avatarBlob' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
});
export const Link = IDL.Record({
  'id' : LinkId,
  'url' : IDL.Text,
  'displayText' : IDL.Text,
  'icon' : IDL.Opt(IDL.Text),
  'orderIndex' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addLink' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat],
      [LinkId],
      [],
    ),
  'deleteLink' : IDL.Func([LinkId], [], []),
  'getProfile' : IDL.Func([], [Profile], ['query']),
  'listLinks' : IDL.Func([], [IDL.Vec(Link)], ['query']),
  'setProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'updateLink' : IDL.Func(
      [LinkId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const LinkId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'avatarBlob' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
  });
  const Link = IDL.Record({
    'id' : LinkId,
    'url' : IDL.Text,
    'displayText' : IDL.Text,
    'icon' : IDL.Opt(IDL.Text),
    'orderIndex' : IDL.Nat,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addLink' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat],
        [LinkId],
        [],
      ),
    'deleteLink' : IDL.Func([LinkId], [], []),
    'getProfile' : IDL.Func([], [Profile], ['query']),
    'listLinks' : IDL.Func([], [IDL.Vec(Link)], ['query']),
    'setProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'updateLink' : IDL.Func(
        [LinkId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };